//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeltAdminCommon
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RangeClass", Namespace="http://schemas.datacontract.org/2004/07/FeltAdminCommon")]
    public enum RangeClass : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Range100m = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Range200m = 2,
    }
}
namespace FeltAdminServer.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/FeltAdminServer.Data")]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClassField;
        
        private string ClubNameField;
        
        private FeltAdminServer.Data.FeltHold[] FeltHoldsField;
        
        private int MinneField;
        
        private int MinneInnerField;
        
        private string NameField;
        
        private int ShooterIdField;
        
        private int TotalInnerHitsField;
        
        private string TotalResultField;
        
        private int TotalSumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubName
        {
            get
            {
                return this.ClubNameField;
            }
            set
            {
                this.ClubNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FeltAdminServer.Data.FeltHold[] FeltHolds
        {
            get
            {
                return this.FeltHoldsField;
            }
            set
            {
                this.FeltHoldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Minne
        {
            get
            {
                return this.MinneField;
            }
            set
            {
                this.MinneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinneInner
        {
            get
            {
                return this.MinneInnerField;
            }
            set
            {
                this.MinneInnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShooterId
        {
            get
            {
                return this.ShooterIdField;
            }
            set
            {
                this.ShooterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalInnerHits
        {
            get
            {
                return this.TotalInnerHitsField;
            }
            set
            {
                this.TotalInnerHitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalResult
        {
            get
            {
                return this.TotalResultField;
            }
            set
            {
                this.TotalResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalSum
        {
            get
            {
                return this.TotalSumField;
            }
            set
            {
                this.TotalSumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeltHold", Namespace="http://schemas.datacontract.org/2004/07/FeltAdminServer.Data")]
    public partial class FeltHold : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HitsField;
        
        private int InnerHitsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Hits
        {
            get
            {
                return this.HitsField;
            }
            set
            {
                this.HitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InnerHits
        {
            get
            {
                return this.InnerHitsField;
            }
            set
            {
                this.InnerHitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Registration", Namespace="http://schemas.datacontract.org/2004/07/FeltAdminServer.Data")]
    public partial class Registration : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClassField;
        
        private string ClubNameField;
        
        private string NameField;
        
        private FeltAdminServer.Data.Result ResultField;
        
        private int ShooterIdField;
        
        private int TargetField;
        
        private int TeamField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClubName
        {
            get
            {
                return this.ClubNameField;
            }
            set
            {
                this.ClubNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FeltAdminServer.Data.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShooterId
        {
            get
            {
                return this.ShooterIdField;
            }
            set
            {
                this.ShooterIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Target
        {
            get
            {
                return this.TargetField;
            }
            set
            {
                this.TargetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Team
        {
            get
            {
                return this.TeamField;
            }
            set
            {
                this.TeamField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IFestResultService")]
public interface IFestResultService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetCompetitions", ReplyAction="http://tempuri.org/IFestResultService/GetCompetitionsResponse")]
    string[] GetCompetitions(FeltAdminCommon.RangeClass rangeClass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetCompetitions", ReplyAction="http://tempuri.org/IFestResultService/GetCompetitionsResponse")]
    System.Threading.Tasks.Task<string[]> GetCompetitionsAsync(FeltAdminCommon.RangeClass rangeClass);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetResults", ReplyAction="http://tempuri.org/IFestResultService/GetResultsResponse")]
    FeltAdminServer.Data.Result[] GetResults(FeltAdminCommon.RangeClass rangeClass, string competition);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetResults", ReplyAction="http://tempuri.org/IFestResultService/GetResultsResponse")]
    System.Threading.Tasks.Task<FeltAdminServer.Data.Result[]> GetResultsAsync(FeltAdminCommon.RangeClass rangeClass, string competition);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetRegistrations", ReplyAction="http://tempuri.org/IFestResultService/GetRegistrationsResponse")]
    FeltAdminServer.Data.Registration[] GetRegistrations(FeltAdminCommon.RangeClass rangeClass, string competition);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFestResultService/GetRegistrations", ReplyAction="http://tempuri.org/IFestResultService/GetRegistrationsResponse")]
    System.Threading.Tasks.Task<FeltAdminServer.Data.Registration[]> GetRegistrationsAsync(FeltAdminCommon.RangeClass rangeClass, string competition);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFestResultServiceChannel : IFestResultService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FestResultServiceClient : System.ServiceModel.ClientBase<IFestResultService>, IFestResultService
{
    
    public FestResultServiceClient()
    {
    }
    
    public FestResultServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FestResultServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FestResultServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FestResultServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string[] GetCompetitions(FeltAdminCommon.RangeClass rangeClass)
    {
        return base.Channel.GetCompetitions(rangeClass);
    }
    
    public System.Threading.Tasks.Task<string[]> GetCompetitionsAsync(FeltAdminCommon.RangeClass rangeClass)
    {
        return base.Channel.GetCompetitionsAsync(rangeClass);
    }
    
    public FeltAdminServer.Data.Result[] GetResults(FeltAdminCommon.RangeClass rangeClass, string competition)
    {
        return base.Channel.GetResults(rangeClass, competition);
    }
    
    public System.Threading.Tasks.Task<FeltAdminServer.Data.Result[]> GetResultsAsync(FeltAdminCommon.RangeClass rangeClass, string competition)
    {
        return base.Channel.GetResultsAsync(rangeClass, competition);
    }
    
    public FeltAdminServer.Data.Registration[] GetRegistrations(FeltAdminCommon.RangeClass rangeClass, string competition)
    {
        return base.Channel.GetRegistrations(rangeClass, competition);
    }
    
    public System.Threading.Tasks.Task<FeltAdminServer.Data.Registration[]> GetRegistrationsAsync(FeltAdminCommon.RangeClass rangeClass, string competition)
    {
        return base.Channel.GetRegistrationsAsync(rangeClass, competition);
    }
}
